### ISSUE TITLE
Describe individual pheromone update algorithm and write formula.

### ISSUE THREAD

**Issue by JJ** [sigevo-summer-school-2018/tiger-mosquito-algorithm#9]
Describe how pheromone is updated based on offspring.

**Comment by tushar-semwal** [comment]
How much or how many times a parent or its offspring are chosen (initially based on fitness) during the tournament selection can be represented in the form of its Pheromone-Potential (PP). Initially the value of PP for all the solutions will be *tabula-rasa*. Now, let us select k-best fitness solutions for the tournament. All the k-best will have their PP initialized to 100 (say). Now in the second round of tournament, if the offspring of a parent is selected, the former will be awarded with 100 as PP while the latter's PP will be incremented by `Q^h` (Q is some constant <1 and h is the hierarchy level) of the former's PP. Hierarchy level is incremented based on the level of the parent from the offspring. For e.g. h=0 for a single parent and h=1 for a parent from its immediate child. h=2 for a parent from the child of its offspring.

```python
if x_i selected:
  PP(x_i) += 100
  PP(parents[x_i]) += Q^h*PP(x_i)
````
I will try to explain the rationale for this hierarchical discounted PP below:

Old generations are awarded with high discounted values since they are the initial set of solutions and thus may not be given much importance. Parent with more number of offsprings getting selected in the tournament will get more additions to its PP values from its respective offspring. Thus the solution with higher number of children getting selected could have a high potential in producing good solutions.

@hmonzon @JJ  Not yet finalized the data structures to map the child and the parents but arrays could be our first option. See if there is any method in DEAP. Efficient way of Bookkeeping the parameters is also needed. 
@hmonzon  I will re-structure the formula based on your inputs on DEAP.

**Comment by christian-cl** [comment]
Another option can be measured as the number of direct childrens in orther to avoid the use of too bad solutions.
```
if x_i selected:
  PP(x_i) += 100 + k * size(childrens)
```

I think that these two can be ok, so, to me can e closed if it added to the [algorithm.md](https://github.com/sigevo-summer-school-2018/tiger-mosquito-algorithm/blob/master/algorithm.md) file

**Comment by christian-cl** [comment]
It is the same thing, I have modify the description in the commit 7d73e1938ecb415e21a2f73388296a4dfb97e849
